package com.dayflow.hrms.audit.enums;

public enum AuditAction {
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    LEAVE_CREATED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    PAYROLL_CREATED,
    PAYROLL_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    NOTIFICATION_READ
}
